pub mod attachments;
pub mod cc_switch;
pub mod commands;
pub mod compact;
pub mod context;
pub mod defs;
pub mod detection;
pub mod dsh_profile;
pub mod errors;
pub mod import;
pub mod import_history;
pub mod installer;
pub mod kimi_usage;
pub mod overrides;
pub mod prompt;
pub mod provider_profile;
pub mod registry;
pub mod relay_models;
pub mod run;
pub mod session;
pub mod skill_stage;
pub mod slash;
pub mod spawn;
pub mod stream;
pub mod types;
pub mod workspace;

pub use run::{run_external_cli_reply, run_external_cli_slash_command};
